"""Shared schemas for MOE Toolkit cloud and connector."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from moe_toolkit.local_env import default_public_base_url


class HealthComponent(BaseModel):
    """Represents the status of a single runtime component."""

    name: str
    healthy: bool
    detail: str


class HealthResponse(BaseModel):
    """Cloud health response returned by the service API."""

    service: str
    version: str
    healthy: bool
    authenticated: bool | None = None
    components: list[HealthComponent]


class ConnectorConfig(BaseModel):
    """Local connector configuration persisted on disk."""

    server_url: str = Field(default_factory=default_public_base_url)
    api_key: str = ""
    host_client: str = "cli"
    output_dir: Path = Field(default_factory=lambda: Path.home() / "MOE Outputs")
    request_timeout_seconds: int = 60
    max_upload_size_mb: int = 100
    run_poll_interval_seconds: float = 0.1

    @field_validator("server_url")
    @classmethod
    def validate_server_url(cls, value: str) -> str:
        if not value.startswith(("http://", "https://")):
            raise ValueError("server_url must start with http:// or https://")
        return value.rstrip("/")

    @field_validator("host_client")
    @classmethod
    def validate_host_client(cls, value: str) -> str:
        allowed = {"cli", "claude-code", "codex-cli", "openclaw"}
        if value not in allowed:
            raise ValueError(f"host_client must be one of {sorted(allowed)}")
        return value


class HostInstallResult(BaseModel):
    """Reports the result of host integration changes."""

    host: str
    config_path: Path
    changed: bool
    detail: str


class UploadRef(BaseModel):
    """Metadata for a file uploaded to the cloud service."""

    upload_id: str
    filename: str
    size_bytes: int
    content_type: str
    expires_at: datetime


class RemoteTaskRequest(BaseModel):
    """Represents a connector request for remote execution."""

    task: str
    attachments: list[str]
    session_id: str | None = None
    output_preferences: dict[str, str] = Field(default_factory=dict)


class ArtifactRef(BaseModel):
    """Represents an artifact generated by a run."""

    artifact_id: str
    run_id: str
    filename: str
    media_type: str
    size_bytes: int
    download_url: str


class ToolSummary(BaseModel):
    """Public summary for a curated tool in the registry."""

    tool_id: str
    version: str
    description: str
    capabilities: list[str]
    input_types: list[str]
    output_types: list[str]
    enabled: bool = True
    priority: int = 100


class ToolManifest(ToolSummary):
    """Full manifest used by the curated registry and router."""

    image: str
    network_required: bool = False


class ToolMatch(BaseModel):
    """Represents a router-selected tool candidate."""

    tool_id: str
    image: str
    matched_capabilities: list[str] = Field(default_factory=list)
    score: int = 0
    reason: str = ""


class TelemetryEvent(BaseModel):
    """Telemetry payload accepted from connectors."""

    event_type: str
    host_client: str
    status: str
    tool_id: str | None = None
    tool_version: str | None = None
    run_id: str | None = None
    error_code: str | None = None
    duration_ms: int | None = None
    platform: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @field_validator("host_client")
    @classmethod
    def validate_telemetry_host_client(cls, value: str) -> str:
        allowed = {"cli", "claude-code", "codex-cli", "openclaw"}
        if value not in allowed:
            raise ValueError(f"host_client must be one of {sorted(allowed)}")
        return value


class RoutePlan(BaseModel):
    """Minimal route plan chosen for a run."""

    plan_id: str
    capabilities: list[str]
    selected_images: list[str]
    selected_tools: list[str] = Field(default_factory=list)
    execution_steps: list[str]
    selection_reason: str = ""
    explanation: str


class RunRecord(BaseModel):
    """Execution status for a remote run."""

    run_id: str
    session_id: str | None = None
    status: Literal["queued", "running", "success", "failed"]
    task: str
    route_plan: RoutePlan
    artifact_ids: list[str] = Field(default_factory=list)
    error_code: str | None = None
    detail: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class TaskAccepted(BaseModel):
    """Response returned when a task is accepted for execution."""

    run_id: str
    status: Literal["queued", "running", "success", "failed"]
    route_plan: RoutePlan
