"""Shared schemas for MOE Toolkit cloud and connector."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class HealthComponent(BaseModel):
    """Represents the status of a single runtime component."""

    name: str
    healthy: bool
    detail: str


class HealthResponse(BaseModel):
    """Cloud health response returned by the service API."""

    service: str
    version: str
    healthy: bool
    authenticated: bool | None = None
    components: list[HealthComponent]


class ConnectorConfig(BaseModel):
    """Local connector configuration persisted on disk."""

    server_url: str = "${MOE_PUBLIC_BASE_URL}"
    api_key: str = ""
    host_client: str = "codex-cli"
    output_dir: Path = Field(default_factory=lambda: Path.home() / "MOE Outputs")
    request_timeout_seconds: int = 60
    max_upload_size_mb: int = 100
    run_poll_interval_seconds: float = 0.1

    @field_validator("server_url")
    @classmethod
    def validate_server_url(cls, value: str) -> str:
        if not value.startswith(("http://", "https://")):
            raise ValueError("server_url must start with http:// or https://")
        return value.rstrip("/")

    @field_validator("host_client")
    @classmethod
    def validate_host_client(cls, value: str) -> str:
        allowed = {"claude-code", "codex-cli", "openclaw"}
        if value not in allowed:
            raise ValueError(f"host_client must be one of {sorted(allowed)}")
        return value


class HostInstallResult(BaseModel):
    """Reports the result of host integration changes."""

    host: str
    config_path: Path
    changed: bool
    detail: str


class UploadRef(BaseModel):
    """Metadata for a file uploaded to the cloud service."""

    upload_id: str
    filename: str
    size_bytes: int
    content_type: str
    expires_at: datetime


class RemoteTaskRequest(BaseModel):
    """Represents a connector request for remote execution."""

    task: str
    attachments: list[str]
    session_id: str | None = None
    output_preferences: dict[str, str] = Field(default_factory=dict)


class ArtifactRef(BaseModel):
    """Represents an artifact generated by a run."""

    artifact_id: str
    run_id: str
    filename: str
    media_type: str
    size_bytes: int
    download_url: str


class RoutePlan(BaseModel):
    """Minimal route plan chosen for a run."""

    plan_id: str
    capabilities: list[str]
    selected_images: list[str]
    execution_steps: list[str]
    explanation: str


class RunRecord(BaseModel):
    """Execution status for a remote run."""

    run_id: str
    session_id: str | None = None
    status: Literal["queued", "running", "success", "failed"]
    task: str
    route_plan: RoutePlan
    artifact_ids: list[str] = Field(default_factory=list)
    error_code: str | None = None
    detail: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class TaskAccepted(BaseModel):
    """Response returned when a task is accepted for execution."""

    run_id: str
    status: Literal["queued", "running", "success", "failed"]
    route_plan: RoutePlan
